# Generated by Django 2.0.6 on 2018-07-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180708_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producimage',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='products.ProduCategory'),
        ),
    ]
