# Generated by Django 2.0.7 on 2018-07-06 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_father'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='father',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
    ]
