# Generated by Django 2.0.6 on 2018-07-08 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180708_1316'),
        ('comments', '0002_auto_20180708_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.Product'),
            preserve_default=False,
        ),
    ]
