# Generated by Django 2.0.6 on 2018-07-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioGuia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(upload_to='core', verbose_name='Imagen')),
                ('url', models.URLField(verbose_name='Url')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'EjercicioGuia',
                'verbose_name_plural': 'Ejercicios Guias',
                'ordering': ['-updated'],
            },
        ),
    ]
