# Generated by Django 2.0.7 on 2018-07-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(choices=[('colombia', 'CO'), ('Peru', 'PE'), ('Argentina', 'ARG'), ('Usa', 'USA')], max_length=3, verbose_name='Codigo')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paices',
            },
        ),
    ]
