# Generated by Django 2.0.6 on 2018-06-27 16:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180627_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True, verbose_name='Contenido'),
        ),
    ]
